spring:
  application:
    name: knowledge
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_application?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 206721
  data:
    redis:
      host: 192.168.88.131
      port: 6379
      password: 206721

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false

aliyun:
  oss:
    endpoint: your-endpoint
    accessKeyId: your-key
    accessKeySecret: your-secret
    bucketName: bucket-name

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: aiapplication_knowledge-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1 #同步发送失败尝试次数
    retry-times-when-send-async-failed: 1 #异步发送失败尝试次数

rag:
  collection:
    collection-name: knowledge_default_store
    dimension: 1024
    metric-type: COSINE

milvus:
  uri: http://192.168.88.131:19530
server:
  port: 10030
  address: 0.0.0.0
